<?php

declare(strict_types=1);

namespace App\Job;

use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;

/**
 * A job's identity, as a UUIDv4.
 *
 * A wrapper rather than a bare string because ids are used as array keys
 * throughout - the visibility monitor, the DLQ, the storage log - and a
 * type is what stops a job type or a worker id being passed where a job id
 * belongs. Random rather than sequential so ids can be generated by any
 * producer, in any process, without coordinating.
 */
final readonly class JobId
{
    private function __construct(
        private UuidInterface $uuid,
    ) {
    }

    public static function generate(): self
    {
        return new self(Uuid::uuid4());
    }

    public static function fromString(string $id): self
    {
        return new self(Uuid::fromString($id));
    }

    public function toString(): string
    {
        return $this->uuid->toString();
    }

    public function __toString(): string
    {
        return $this->toString();
    }
}
